export const BLOOD_STORE_REQUEST = 'BLOOD_STORE_REQUEST'
export const BLOOD_STORE_SUCCESS = 'BLOOD_STORE_SUCCESS'
export const BLOOD_STORE_FAIL = 'BLOOD_STORE_FAIL'
export const BLOOD_STORE_RESET = 'BLOOD_STORE_RESET'

export const BLOOD_STORE_CREATE_REQUEST = 'BLOOD_STORE_CREATE_REQUEST'
export const BLOOD_STORE_CREATE_SUCCESS = 'BLOOD_STORE_CREATE_SUCCESS'
export const BLOOD_STORE_CREATE_FAIL = 'BLOOD_STORE_CREATE_FAIL'
export const BLOOD_STORE_CREATE_RESET = 'BLOOD_STORE_CREATE_RESET'

export const BLOOD_STORE_UPDATE_REQUEST = 'BLOOD_STORE_UPDATE_REQUEST'
export const BLOOD_STORE_UPDATE_SUCCESS = 'BLOOD_STORE_UPDATE_SUCCESS'
export const BLOOD_STORE_UPDATE_FAIL = 'BLOOD_STORE_UPDATE_FAIL'
export const BLOOD_STORE_UPDATE_RESET = 'BLOOD_STORE_UPDATE_RESET'

export const BLOOD_STORE_DELETE_REQUEST = 'BLOOD_STORE_DELETE_REQUEST'
export const BLOOD_STORE_DELETE_SUCCESS = 'BLOOD_STORE_DELETE_SUCCESS'
export const BLOOD_STORE_DELETE_FAIL = 'BLOOD_STORE_DELETE_FAIL'
export const BLOOD_STORE_DELETE_RESET = 'BLOOD_STORE_DELETE_RESET'
