export const BLOOD_REQUEST_REQUEST = 'BLOOD_REQUEST_REQUEST'
export const BLOOD_REQUEST_SUCCESS = 'BLOOD_REQUEST_SUCCESS'
export const BLOOD_REQUEST_FAIL = 'BLOOD_REQUEST_FAIL'
export const BLOOD_REQUEST_RESET = 'BLOOD_REQUEST_RESET'

export const BLOOD_REQUEST_CREATE_REQUEST = 'BLOOD_REQUEST_CREATE_REQUEST'
export const BLOOD_REQUEST_CREATE_SUCCESS = 'BLOOD_REQUEST_CREATE_SUCCESS'
export const BLOOD_REQUEST_CREATE_FAIL = 'BLOOD_REQUEST_CREATE_FAIL'
export const BLOOD_REQUEST_CREATE_RESET = 'BLOOD_REQUEST_CREATE_RESET'

export const BLOOD_REQUEST_UPDATE_REQUEST = 'BLOOD_REQUEST_UPDATE_REQUEST'
export const BLOOD_REQUEST_UPDATE_SUCCESS = 'BLOOD_REQUEST_UPDATE_SUCCESS'
export const BLOOD_REQUEST_UPDATE_FAIL = 'BLOOD_REQUEST_UPDATE_FAIL'
export const BLOOD_REQUEST_UPDATE_RESET = 'BLOOD_REQUEST_UPDATE_RESET'

export const BLOOD_REQUEST_DELETE_REQUEST = 'BLOOD_REQUEST_DELETE_REQUEST'
export const BLOOD_REQUEST_DELETE_SUCCESS = 'BLOOD_REQUEST_DELETE_SUCCESS'
export const BLOOD_REQUEST_DELETE_FAIL = 'BLOOD_REQUEST_DELETE_FAIL'
export const BLOOD_REQUEST_DELETE_RESET = 'BLOOD_REQUEST_DELETE_RESET'
