export const BLOOD_ISSUE_REQUEST = 'BLOOD_ISSUE_REQUEST'
export const BLOOD_ISSUE_SUCCESS = 'BLOOD_ISSUE_SUCCESS'
export const BLOOD_ISSUE_FAIL = 'BLOOD_ISSUE_FAIL'
export const BLOOD_ISSUE_RESET = 'BLOOD_ISSUE_RESET'

export const BLOOD_ISSUE_CREATE_REQUEST = 'BLOOD_ISSUE_CREATE_REQUEST'
export const BLOOD_ISSUE_CREATE_SUCCESS = 'BLOOD_ISSUE_CREATE_SUCCESS'
export const BLOOD_ISSUE_CREATE_FAIL = 'BLOOD_ISSUE_CREATE_FAIL'
export const BLOOD_ISSUE_CREATE_RESET = 'BLOOD_ISSUE_CREATE_RESET'

export const BLOOD_ISSUE_DELETE_REQUEST = 'BLOOD_ISSUE_DELETE_REQUEST'
export const BLOOD_ISSUE_DELETE_SUCCESS = 'BLOOD_ISSUE_DELETE_SUCCESS'
export const BLOOD_ISSUE_DELETE_FAIL = 'BLOOD_ISSUE_DELETE_FAIL'
export const BLOOD_ISSUE_DELETE_RESET = 'BLOOD_ISSUE_DELETE_RESET'
